

services:
  web:
    build:
      context: .
    # command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - ./db.sqlite3:/app/db.sqlite3  # Persist SQLite database
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
